import { Commissioner } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

import "./globals.css";
import Avatar from "@/assets/images/avatar.jpg";

// Configuración de la fuente
const commissioner = Commissioner({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${commissioner.className} bg-slate-50`}>
        <main className="grid min-h-screen items-center py-20">
          <div className="mx-auto rounded-md bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-1 sm:w-[500px] md:w-[700px]">
            <div className="rounded bg-slate-100 p-8">
              <Link href="/">
                <div className="mx-auto -mt-20 mb-8 h-24 w-24 overflow-hidden rounded-full">
                  <Image
                    src={Avatar}
                    alt="Fotografia de perfil"
                    className="object-cover"
                    width={96}
                    height={96}
                    priority
                  />
                </div>
              </Link>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
